version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://namnguyenhoang0903:01202902494@cluster-for-airbnb.pqjitkv.mongodb.net/test
      - NODE_ENV=production
      - NEXTAUTH_URL=do-an-c-nweb.vercel.app
      # Add other environment variables as needed
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    # Uncomment and modify if you need authentication
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=username
    #   - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
